# Generated by Django 4.2.1 on 2023-05-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_rename_content_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='content',
        ),
    ]
