# Generated by Django 4.2.1 on 2024-09-09 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otpmodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 16, 6, 36, 409679)),
        ),
    ]
